/**
 * @nevent/chatbot - TypeScript type definitions
 *
 * Comprehensive type system for the Nevent embeddable chatbot widget SDK.
 * These types define the full contract between the chatbot widget, the
 * Nevent API, and the host application.
 *
 * @packageDocumentation
 */

import type { ApiError } from '@nevent/core';
import type { AuthConfig, UserIdentity } from './chatbot/auth-manager';

// ============================================================================
// Enums & Union Types
// ============================================================================

/**
 * Position of the floating chat bubble on the page.
 * Controls which corner of the viewport the bubble appears in.
 */
export type BubblePosition = 'bottom-right' | 'bottom-left';

/**
 * Theme mode for the chatbot widget appearance.
 *
 * - `'light'` - Light background with dark text (default)
 * - `'dark'` - Dark background with light text
 * - `'auto'` - Follows the user's system preference via `prefers-color-scheme`
 */
export type ThemeMode = 'light' | 'dark' | 'auto';

/**
 * Supported locales for the chatbot UI strings.
 * Controls labels, placeholders, and system messages language.
 */
export type SupportedLocale = 'es' | 'en' | 'ca' | 'pt';

/**
 * Role of a chat message participant.
 *
 * - `'user'` - Message sent by the end user
 * - `'assistant'` - Message generated by the AI chatbot
 * - `'system'` - System-generated message (e.g., welcome message, status updates)
 */
export type MessageRole = 'user' | 'assistant' | 'system';

/**
 * Type of content within a chat message.
 *
 * - `'text'` - Plain text message
 * - `'rich'` - Rich content (cards, carousels, images)
 * - `'quick_reply'` - Message with quick reply action buttons
 * - `'system'` - System notification (e.g., conversation started)
 */
export type MessageType = 'text' | 'rich' | 'quick_reply' | 'system';

/**
 * Delivery status of a sent message.
 *
 * - `'sending'` - Message is being transmitted to the server
 * - `'sent'` - Message has been received by the server
 * - `'delivered'` - Message has been processed and response is expected
 * - `'error'` - Message failed to send
 */
export type MessageStatus = 'sending' | 'sent' | 'delivered' | 'error';

/**
 * Status of a conversation session.
 *
 * - `'active'` - Conversation is ongoing and accepts new messages
 * - `'closed'` - Conversation has been ended by user or system
 * - `'archived'` - Conversation is stored for historical reference
 */
export type ConversationStatus = 'active' | 'closed' | 'archived';

/**
 * Type of rich content that can be embedded in a message.
 *
 * - `'card'` - Single card with title, description, image, and action buttons
 * - `'carousel'` - Horizontal scrollable set of cards
 * - `'image'` - Standalone image with optional alt text
 * - `'button_group'` - Group of action buttons without card context
 */
export type RichContentType = 'card' | 'carousel' | 'image' | 'button_group';

/**
 * Type of action triggered by an action button.
 *
 * - `'url'` - Opens a URL in a new tab
 * - `'postback'` - Sends a value back to the chatbot as a user message
 * - `'phone'` - Initiates a phone call
 * - `'copy'` - Copies text to clipboard
 */
export type ActionButtonType = 'url' | 'postback' | 'phone' | 'copy';

/**
 * Analytics event types tracked by the chatbot widget.
 * Used to measure engagement and identify usage patterns.
 */
export type ChatbotEventType =
  | 'chatbot_loaded'
  | 'chatbot_opened'
  | 'chatbot_closed'
  | 'chatbot_error'
  | 'conversation_started'
  | 'conversation_resumed'
  | 'message_sent'
  | 'message_received'
  | 'quick_reply_clicked'
  | 'rich_content_clicked'
  | 'link_clicked'
  | 'typing_started'
  | 'typing_stopped';

/**
 * Font type for custom typography configuration.
 */
export type FontType = 'GOOGLE_FONT' | 'CUSTOM_FONT' | 'SYSTEM_FONT';

// ============================================================================
// Font Configuration
// ============================================================================

/**
 * Font configuration for text elements.
 * Supports Google Fonts, custom uploaded fonts, and system fonts.
 */
export interface FontConfig {
  /** CSS font-family value (e.g., 'Inter', 'Roboto') */
  family?: string;
  /** Font category for fallback (e.g., 'sans-serif', 'serif') */
  category?: string;
  /** Source type of the font */
  type?: FontType;
  /** Custom font ID for uploaded fonts */
  customFontId?: string;
  /** Font file URLs keyed by weight/style (e.g., '400': 'url', '700': 'url') */
  files?: Record<string, string>;
}

// ============================================================================
// Style Configuration
// ============================================================================

/**
 * Visual styling for the floating chat bubble (FAB - Floating Action Button).
 * The bubble is the circular button that toggles the chat window.
 */
export interface BubbleStyles {
  /** Background color of the bubble. Default: '#007bff' */
  backgroundColor?: string;
  /** Color of the chat icon inside the bubble. Default: '#ffffff' */
  iconColor?: string;
  /** Diameter of the bubble in pixels. Default: 60 */
  size?: number;
  /** CSS box-shadow value. Default: '0 4px 12px rgba(0,0,0,0.15)' */
  shadow?: string;
  /** Distance from the bottom of the viewport in pixels. Default: 20 */
  bottom?: number;
  /** Distance from the right (or left for bottom-left position) in pixels. Default: 20 */
  right?: number;
  /** Border radius override in pixels. Defaults to circular (size / 2) */
  borderRadius?: number;
  /** Notification badge background color. Default: '#ff4444' */
  badgeColor?: string;
  /** Notification badge text color. Default: '#ffffff' */
  badgeTextColor?: string;
}

/**
 * Visual styling for the main chat window container.
 */
export interface WindowStyles {
  /** Width of the chat window in pixels. Default: 400 */
  width?: number;
  /** Height of the chat window in pixels. Default: 600 */
  height?: number;
  /** Border radius of the window corners in pixels. Default: 16 */
  borderRadius?: number;
  /** CSS box-shadow value. Default: '0 8px 32px rgba(0,0,0,0.12)' */
  shadow?: string;
  /** Background color of the chat window body. Default: '#ffffff' (light) / '#1a1a2e' (dark) */
  backgroundColor?: string;
  /** Distance from the bottom of the viewport in pixels (floating mode). Default: 90 */
  bottom?: number;
  /** Distance from the right/left in pixels (floating mode). Default: 20 */
  right?: number;
}

/**
 * Visual styling for the chat window header bar.
 */
export interface HeaderStyles {
  /** Background color of the header. Default: '#007bff' */
  backgroundColor?: string;
  /** Color of the header title text. Default: '#ffffff' */
  textColor?: string;
  /** Color of the header subtitle/status text. Default: 'rgba(255,255,255,0.8)' */
  subtitleColor?: string;
  /** Font configuration for header text */
  font?: FontConfig;
  /** Font size for the title. Default: '16px' */
  fontSize?: string;
  /** Height of the header in pixels. Default: 64 */
  height?: number;
  /** Whether to show the close button. Default: true */
  showCloseButton?: boolean;
  /** Whether to show the avatar in the header. Default: true */
  showAvatar?: boolean;
}

/**
 * Visual styling for chat message bubbles.
 */
export interface MessageStyles {
  /** Background color of user message bubbles. Default: '#007bff' */
  userBubbleColor?: string;
  /** Text color within user message bubbles. Default: '#ffffff' */
  userTextColor?: string;
  /** Background color of bot/assistant message bubbles. Default: '#f0f0f0' */
  botBubbleColor?: string;
  /** Text color within bot/assistant message bubbles. Default: '#333333' */
  botTextColor?: string;
  /** Font configuration for message text */
  font?: FontConfig;
  /** Font size for message content. Default: '14px' */
  fontSize?: string;
  /** Line height for message content. Default: '1.5' */
  lineHeight?: string;
  /** Border radius for message bubbles in pixels. Default: 12 */
  borderRadius?: number;
  /** Padding inside message bubbles. Default: '10px 14px' */
  padding?: string;
  /** Maximum width of a message bubble as percentage. Default: '80%' */
  maxWidth?: string;
  /** Whether to show timestamps on messages. Default: true */
  showTimestamp?: boolean;
  /** Whether to show the bot avatar next to messages. Default: true */
  showAvatar?: boolean;
  /** Color for system messages. Default: '#888888' */
  systemMessageColor?: string;
}

/**
 * Visual styling for the message input area.
 */
export interface InputStyles {
  /** Background color of the input field. Default: '#ffffff' */
  backgroundColor?: string;
  /** Text color of the input field. Default: '#333333' */
  textColor?: string;
  /** Border color of the input field. Default: '#e0e0e0' */
  borderColor?: string;
  /** Border radius of the input field. Default: '24px' */
  borderRadius?: string;
  /** Font configuration for input text */
  font?: FontConfig;
  /** Font size for input text. Default: '14px' */
  fontSize?: string;
  /** Padding inside the input field. Default: '12px 16px' */
  padding?: string;
  /** Height of the input area container. Default: '56px' */
  height?: string;
  /** Background color of the send button. Default: '#007bff' */
  sendButtonColor?: string;
  /** Icon color of the send button. Default: '#ffffff' */
  sendButtonIconColor?: string;
  /** Placeholder text color. Default: '#999999' */
  placeholderColor?: string;
  /** Focus border color. Default: '#007bff' */
  focusBorderColor?: string;
}

/**
 * Visual styling for quick reply buttons.
 */
export interface QuickReplyStyles {
  /** Background color of quick reply buttons. Default: 'transparent' */
  backgroundColor?: string;
  /** Text color of quick reply buttons. Default: '#007bff' */
  textColor?: string;
  /** Border color of quick reply buttons. Default: '#007bff' */
  borderColor?: string;
  /** Border radius of quick reply buttons. Default: '16px' */
  borderRadius?: string;
  /** Font size for quick reply text. Default: '13px' */
  fontSize?: string;
  /** Hover background color. Default: '#007bff' */
  hoverBackgroundColor?: string;
  /** Hover text color. Default: '#ffffff' */
  hoverTextColor?: string;
}

/**
 * Visual styling for the typing indicator animation.
 */
export interface TypingIndicatorStyles {
  /** Color of the animated dots. Default: '#999999' */
  dotColor?: string;
  /** Size of each dot in pixels. Default: 8 */
  dotSize?: number;
  /** Background color of the typing indicator container. Default: '#f0f0f0' */
  backgroundColor?: string;
}

/**
 * Complete chatbot styles configuration.
 * Allows granular visual customization of every widget component.
 *
 * @example
 * ```typescript
 * const styles: ChatbotStyles = {
 *   bubble: { backgroundColor: '#6366f1', size: 64 },
 *   header: { backgroundColor: '#6366f1' },
 *   messages: { userBubbleColor: '#6366f1' },
 *   fontFamily: 'Inter, sans-serif',
 * };
 * ```
 */
export interface ChatbotStyles {
  /** Styles for the floating chat bubble (FAB) */
  bubble?: BubbleStyles;
  /** Styles for the main chat window container */
  window?: WindowStyles;
  /** Styles for the chat window header */
  header?: HeaderStyles;
  /** Styles for chat message bubbles */
  messages?: MessageStyles;
  /** Styles for the message input area */
  input?: InputStyles;
  /** Styles for quick reply buttons */
  quickReplies?: QuickReplyStyles;
  /** Styles for the typing indicator */
  typingIndicator?: TypingIndicatorStyles;
  /** Global font family override applied to all text elements */
  fontFamily?: string;
  /** Global base font size. Default: '14px' */
  fontSize?: string;
  /** Global border radius override in pixels */
  borderRadius?: string;
  /** CSS z-index for the widget layer. Default: 9999 */
  zIndex?: number;
  /** Custom CSS string injected into the widget shadow DOM or style tag */
  customCSS?: string;
}

// ============================================================================
// Typing Status Types
// ============================================================================

/**
 * Configuration for bidirectional typing status notifications.
 *
 * Controls whether the widget sends "user is typing" notifications to the
 * server and how aggressively it debounces those notifications to avoid
 * spamming the backend with keystroke-level events.
 *
 * The server→client direction (agent/bot typing) is handled via SSE events
 * and does not require additional configuration.
 *
 * @example
 * ```typescript
 * const config: TypingStatusConfig = {
 *   enabled: true,
 *   debounceMs: 2000,
 *   timeoutMs: 5000,
 * };
 * ```
 */
export interface TypingStatusConfig {
  /** Whether typing status notifications are enabled. Default: true */
  enabled?: boolean;
  /**
   * Debounce interval in milliseconds between typing notifications.
   * After the first "typing start" is sent, subsequent keystrokes within
   * this window do NOT trigger additional requests. Default: 2000
   */
  debounceMs?: number;
  /**
   * Auto-stop timeout in milliseconds. If no keystroke occurs within this
   * duration after the last notification, a "typing stop" is sent
   * automatically. Default: 5000
   */
  timeoutMs?: number;
}

/**
 * Typing status event received from the server via SSE.
 *
 * Emitted when a live agent or bot starts/stops typing in the conversation.
 * The widget uses this to show "{name} is typing..." in the typing indicator.
 */
export interface TypingStatusEvent {
  /** User/visitor ID of the person typing (for multi-user scenarios) */
  userId?: string;
  /** Agent ID when a live agent is typing */
  agentId?: string;
  /** Whether the agent/bot is currently typing */
  isTyping: boolean;
  /** Display name to show (e.g., "Agent Carlos", "Support") */
  displayName?: string;
}

// ============================================================================
// File Upload Types
// ============================================================================

/**
 * Represents a file attached to a chat message.
 *
 * Tracks the full lifecycle of an attachment from selection through upload
 * completion: pending (selected but not yet uploading), uploading (in-flight
 * with progress updates), uploaded (CDN URL available), or error.
 *
 * For image files, a local `thumbnailUrl` blob URL is created for instant
 * preview before the upload completes. Consumers must call
 * `FileUploadService.revokePreview()` to release the blob URL and avoid
 * memory leaks.
 */
export interface FileAttachment {
  /** Unique identifier for this attachment (UUID) */
  id: string;
  /** The original File object from the user's file picker or drop */
  file: File;
  /** Display name of the file (may differ from `file.name` if sanitized) */
  name: string;
  /** File size in bytes */
  size: number;
  /** MIME type of the file (e.g. 'image/png', 'application/pdf') */
  type: string;
  /** CDN URL of the uploaded file (populated after successful upload) */
  url?: string;
  /** Local blob URL for image preview (populated immediately for image files) */
  thumbnailUrl?: string;
  /** Current upload lifecycle status */
  status: 'pending' | 'uploading' | 'uploaded' | 'error';
  /** Upload progress percentage (0-100) */
  progress: number;
  /** Error message when status is 'error' */
  error?: string;
}

/**
 * Configuration for file upload functionality in the chatbot widget.
 *
 * Controls which file types are accepted, size limits, maximum number of
 * files per message, and the upload endpoint URL.
 *
 * @example
 * ```typescript
 * const config: FileUploadConfig = {
 *   enabled: true,
 *   maxFileSize: 5 * 1024 * 1024, // 5MB
 *   maxFiles: 3,
 *   acceptedTypes: ['image/*', 'application/pdf'],
 * };
 * ```
 */
export interface FileUploadConfig {
  /** Whether file uploads are enabled. Default: true */
  enabled?: boolean;
  /** Maximum file size in bytes. Default: 10MB (10 * 1024 * 1024) */
  maxFileSize?: number;
  /** Maximum number of files per message. Default: 5 */
  maxFiles?: number;
  /** Accepted MIME type patterns. Default: ['image/*', 'application/pdf', 'text/plain'] */
  acceptedTypes?: string[];
  /** Override the upload endpoint URL. Default: '{apiUrl}/chatbot/upload' */
  uploadEndpoint?: string;
}

// ============================================================================
// Message & Conversation Types
// ============================================================================

/**
 * Represents a single chat message within a conversation.
 *
 * Messages can contain plain text, rich content (cards, carousels),
 * and/or quick reply suggestions. Each message has delivery status
 * tracking and optional metadata.
 */
export interface ChatMessage {
  /** Unique message identifier (UUID) */
  id: string;
  /** ID of the conversation this message belongs to */
  conversationId: string;
  /** Role of the message sender */
  role: MessageRole;
  /** Plain text content of the message */
  content: string;
  /** Content type classification */
  type: MessageType;
  /** Rich content payload (cards, carousels, images) */
  richContent?: RichContent;
  /** Quick reply options displayed after this message */
  quickReplies?: QuickReply[];
  /** ISO 8601 timestamp of when the message was created */
  timestamp: string;
  /** Current delivery status of the message */
  status?: MessageStatus;
  /** File attachments included with this message */
  attachments?: FileAttachment[];
  /** Additional metadata attached to the message */
  metadata?: Record<string, unknown>;
}

/**
 * Rich content embedded within a chat message.
 * Supports cards with images/buttons, carousels, standalone images,
 * and button groups.
 *
 * @example
 * ```typescript
 * // Card with action buttons
 * const card: RichContent = {
 *   type: 'card',
 *   title: 'Festival Pass',
 *   description: 'Get your 3-day festival pass',
 *   imageUrl: 'https://example.com/pass.jpg',
 *   buttons: [
 *     { id: '1', label: 'Buy Now', type: 'url', value: 'https://tickets.example.com' }
 *   ],
 * };
 * ```
 */
export interface RichContent {
  /** Type of rich content */
  type: RichContentType;
  /** Card title text */
  title?: string;
  /** Card description or body text */
  description?: string;
  /** URL of the card header image */
  imageUrl?: string;
  /** Action buttons displayed at the bottom of the card */
  buttons?: ActionButton[];
  /** Child items for carousel type (array of card-type RichContent) */
  items?: RichContent[];
  /** Image URL for standalone image type */
  url?: string;
  /** Alt text for images (accessibility) */
  alt?: string;
  /** Aspect ratio for images (e.g., '16:9', '1:1'). Default: 'auto' */
  aspectRatio?: string;
}

/**
 * An action button within rich content or quick replies.
 * Triggers navigation, postback messages, phone calls, or clipboard copies.
 */
export interface ActionButton {
  /** Unique button identifier */
  id: string;
  /** Button label text displayed to the user */
  label: string;
  /** Action type that determines behavior on click */
  type: ActionButtonType;
  /** Action value: URL, postback payload, phone number, or text to copy */
  value: string;
  /** Optional icon identifier or URL */
  icon?: string;
  /** Optional CSS class for custom styling */
  cssClass?: string;
}

/**
 * Quick reply option displayed as a tappable chip below a bot message.
 * Quick replies allow users to respond with predefined options without typing.
 */
export interface QuickReply {
  /** Unique quick reply identifier */
  id: string;
  /** Display text shown on the button */
  label: string;
  /** Value sent as user message when clicked */
  value: string;
  /** Optional icon identifier or emoji */
  icon?: string;
}

/**
 * Represents a complete conversation session between a user and the chatbot.
 */
export interface Conversation {
  /** Unique conversation identifier (UUID) */
  id: string;
  /** ID of the chatbot this conversation belongs to */
  chatbotId: string;
  /** Current status of the conversation */
  status: ConversationStatus;
  /** Ordered list of messages in the conversation */
  messages: ChatMessage[];
  /** ISO 8601 timestamp of when the conversation was created */
  createdAt: string;
  /** ISO 8601 timestamp of the last activity */
  updatedAt: string;
  /** Additional metadata attached to the conversation */
  metadata?: Record<string, unknown>;
}

// ============================================================================
// Server Configuration (from API)
// ============================================================================

/**
 * Theme configuration returned by the server.
 * Defines the visual identity configured by the event promoter in nev-admin-web.
 */
export interface ThemeConfig {
  /** Primary brand color (hex). Default: '#007bff' */
  primaryColor: string;
  /** Secondary accent color (hex) */
  secondaryColor?: string;
  /** Background color for the widget */
  backgroundColor?: string;
  /** Text color for primary content */
  textColor?: string;
  /** Font family configured for the chatbot */
  fontFamily?: string;
  /** Font configuration with full details */
  font?: FontConfig;
  /** Border radius for UI elements in pixels */
  borderRadius?: number;
  /** Theme mode selected by the promoter */
  mode?: ThemeMode;
}

/**
 * Feature flags controlling chatbot capabilities.
 * Managed server-side by the Nevent platform.
 */
export interface FeatureFlags {
  /** Whether quick replies are enabled. Default: true */
  quickReplies: boolean;
  /** Whether rich content (cards, carousels) is enabled. Default: false */
  richContent: boolean;
  /** Whether conversation persistence is enabled. Default: true */
  persistence: boolean;
  /** Whether the typing indicator is shown. Default: true */
  typingIndicator: boolean;
  /** Whether file attachments are supported. Default: false */
  fileAttachments: boolean;
  /** Whether message reactions are enabled. Default: false */
  reactions: boolean;
  /** Whether the chatbot can suggest related events. Default: false */
  eventSuggestions: boolean;
  /** Whether streaming responses (SSE) are enabled. Default: false */
  streaming: boolean;
  /** Whether "Powered by Nevent" branding is shown. Default: true */
  showBranding: boolean;
}

/**
 * Rate limit configuration for API calls.
 * Prevents abuse and ensures fair usage across tenants.
 */
export interface RateLimitConfig {
  /** Maximum messages per minute per conversation. Default: 20 */
  messagesPerMinute: number;
  /** Maximum conversations per hour per visitor. Default: 5 */
  conversationsPerHour: number;
  /** Minimum interval between messages in milliseconds. Default: 1000 */
  minMessageInterval: number;
  /** Maximum message length in characters. Default: 500 */
  maxMessageLength: number;
}

/**
 * Server-side chatbot configuration returned by the config API endpoint.
 * Contains all settings configured by the event promoter in nev-admin-web.
 *
 * Fetched from: `GET /public/chatbot/{chatbotId}/config?tenantId={tenantId}`
 */
export interface ServerChatbotConfig {
  /** Chatbot identifier */
  chatbotId: string;
  /** Tenant identifier for multi-tenancy */
  tenantId: string;
  /** Display name shown in the chat header */
  name: string;
  /** Optional description/subtitle shown below the name */
  description?: string;
  /** Welcome message displayed when conversation starts */
  welcomeMessage: string;
  /** Placeholder text for the input field */
  placeholder: string;
  /** Avatar image URL displayed in the header and next to bot messages */
  avatar?: string;
  /** Visual theme configuration */
  theme: ThemeConfig;
  /** Feature flags controlling available capabilities */
  features: FeatureFlags;
  /** Rate limiting configuration */
  rateLimit: RateLimitConfig;
  /** API authentication token for subsequent API calls */
  token: string;
  /** Custom styles override from server configuration */
  styles?: ChatbotStyles;
  /** Custom CSS injected from server configuration */
  customCSS?: string;
}

// ============================================================================
// Widget Configuration (Client-Side)
// ============================================================================

/**
 * Main configuration interface for the ChatbotWidget.
 *
 * This is the primary configuration object passed by the host application
 * when creating a new chatbot widget instance. Only `chatbotId` and `tenantId`
 * are required; all other options have sensible defaults.
 *
 * @example
 * ```typescript
 * // Minimal configuration
 * const widget = new ChatbotWidget({
 *   chatbotId: 'bot-123',
 *   tenantId: 'tenant-456',
 * });
 *
 * // Full configuration
 * const widget = new ChatbotWidget({
 *   chatbotId: 'bot-123',
 *   tenantId: 'tenant-456',
 *   apiUrl: 'https://api.nevent.es',
 *   position: 'bottom-right',
 *   theme: 'auto',
 *   locale: 'en',
 *   styles: {
 *     bubble: { backgroundColor: '#6366f1' },
 *     header: { backgroundColor: '#6366f1' },
 *   },
 *   onMessage: (msg) => console.log('New message:', msg),
 *   onError: (err) => console.error('Chatbot error:', err),
 * });
 *
 * await widget.init();
 * ```
 */
export interface ChatbotConfig {
  // === Required ===
  /** Chatbot identifier from the Nevent platform */
  chatbotId: string;
  /** Tenant identifier for multi-tenancy */
  tenantId: string;

  // === API Configuration ===
  /** Base URL for API requests. Default: 'https://api.nevent.es' */
  apiUrl?: string;
  /**
   * DOM element ID to mount the widget into.
   * When null (default), the widget renders as a floating bubble.
   * When set, the widget renders inline within the specified container.
   */
  containerId?: string | null;

  // === Appearance ===
  /** Position of the floating bubble. Default: 'bottom-right' */
  position?: BubblePosition;
  /** Color theme mode. Default: 'light' */
  theme?: ThemeMode;
  /** Locale for UI strings. Default: 'es' */
  locale?: SupportedLocale;
  /** Avatar image URL override. Falls back to server-configured avatar when not provided. */
  avatar?: string;
  /** Custom visual style overrides */
  styles?: ChatbotStyles;
  /**
   * Named theme preset to apply (e.g. 'midnight', 'ocean', 'sunset').
   * When provided, overrides the base light/dark token layer with the preset's
   * design tokens. The preset is applied after the base CSS is injected so it
   * takes precedence. Built-in presets: 'light', 'dark', 'midnight', 'ocean',
   * 'sunset', 'forest', 'rose'. Custom presets can be registered via
   * `registerThemePreset` from `@nevent/chatbot/theme-presets`.
   */
  themePreset?: string;
  /**
   * Brand color to auto-generate a complete theme from a single hex color.
   * When provided, `generateThemeFromColor` is used to compute a full set of
   * complementary design tokens using HSL manipulation.
   * Takes precedence over `themePreset` if both are specified.
   * Example: '#6366F1'
   */
  brandColor?: string;
  /**
   * Custom CSS string injected after all base widget styles.
   * Allows fine-grained visual overrides without modifying the SDK.
   * Dangerous patterns (@import, expression(), behavior:) are stripped
   * automatically before injection.
   */
  customCSS?: string;
  /**
   * Custom fonts to load when the widget initialises.
   * Each entry is a `FontConfig` that can specify a Google Font
   * (type: 'GOOGLE_FONT') or a custom @font-face font (type: 'CUSTOM_FONT').
   * Fonts are loaded via the `FontLoader` class and applied via the
   * `--nev-cb-font-family` CSS custom property.
   */
  fonts?: FontConfig[];

  // === Typing Status ===
  /**
   * Configuration for bidirectional typing status notifications.
   *
   * When enabled, the widget notifies the server when the user starts and
   * stops typing, allowing live agent dashboards to display "User is typing..."
   * in real-time. The server→client direction (agent typing) is handled via
   * SSE events regardless of this setting.
   *
   * @example
   * ```typescript
   * typingStatus: {
   *   enabled: true,
   *   debounceMs: 2000,
   *   timeoutMs: 5000,
   * }
   * ```
   */
  typingStatus?: TypingStatusConfig;

  // === File Upload ===
  /**
   * Configuration for file/image upload functionality.
   *
   * When provided (or when `enabled` is not explicitly `false`), the chatbot
   * displays an attachment button next to the send button and supports
   * drag-and-drop and clipboard paste for file uploads.
   *
   * Files are uploaded to `{apiUrl}/chatbot/upload` (or the configured
   * `uploadEndpoint`) as multipart/form-data with an `X-Tenant-ID` header.
   *
   * @example
   * ```typescript
   * fileUpload: {
   *   maxFileSize: 5 * 1024 * 1024, // 5MB
   *   maxFiles: 3,
   *   acceptedTypes: ['image/*', 'application/pdf'],
   * }
   * ```
   */
  fileUpload?: FileUploadConfig;

  // === Sentry Error Reporting ===
  /**
   * Configuration for lightweight Sentry error reporting.
   *
   * When provided (or when not explicitly disabled), errors caught by the
   * ErrorBoundary are automatically forwarded to Sentry for tracking.
   * Uses a lightweight custom implementation (~3KB) instead of the full
   * `@sentry/browser` to avoid bundle bloat and host-page conflicts.
   *
   * By default, errors are sent through the Nevent diagnostics tunnel
   * endpoint (`{apiUrl}/diagnostics`) to bypass ad-blockers.
   *
   * @example
   * ```typescript
   * sentry: {
   *   enabled: true,
   *   sampleRate: 0.5,  // Report 50% of errors
   *   beforeSend: (event) => {
   *     // Filter out known non-critical errors
   *     if (event.exception?.values?.[0]?.value?.includes('ResizeObserver')) {
   *       return null;
   *     }
   *     return event;
   *   },
   * }
   * ```
   */
  sentry?: {
    /** Whether Sentry reporting is enabled. Default: true */
    enabled?: boolean;
    /** Sentry DSN. Default: Nevent's shared SDK DSN */
    dsn?: string;
    /** Tunnel URL for bypassing ad-blockers. Default: `{apiUrl}/diagnostics` */
    tunnel?: string;
    /** Environment tag. Default: auto-detected from apiUrl */
    environment?: string;
    /** Sample rate (0-1). Default: 1.0 */
    sampleRate?: number;
    /** Pre-send filter/modifier hook */
    beforeSend?: (event: unknown) => unknown | null;
  };

  // === Analytics ===
  /** Enable analytics event tracking. Default: true */
  analytics?: boolean;
  /** Analytics ingestion endpoint URL. Default: 'https://events.neventapis.com' */
  analyticsUrl?: string;
  /** Enable debug logging to console. Default: false */
  debug?: boolean;

  // === Behavior ===
  /** Override the server-configured welcome message */
  welcomeMessage?: string;
  /** Override the input field placeholder text */
  placeholder?: string;
  /** Automatically open the chat window on page load. Default: false */
  autoOpen?: boolean;
  /** Delay in milliseconds before auto-opening. Default: 3000 */
  autoOpenDelay?: number;
  /** Persist conversation state in localStorage. Default: true */
  persistConversation?: boolean;
  /** Time-to-live for persisted conversations in hours. Default: 24 */
  conversationTTL?: number;
  /** Show "Powered by Nevent" branding. Default: true */
  showBranding?: boolean;

  // === Backend Context ===
  /**
   * Event ID for scoping the chatbot conversation to a specific event.
   *
   * When provided, the backend uses it to scope the thread (conversation
   * history) to a specific event, preventing context mixing across events.
   * Sent as a query parameter to the streaming and send-message endpoints.
   */
  eventId?: string;

  /**
   * Session source identifier for unauthenticated (guest) users.
   *
   * A UUID that uniquely identifies the anonymous user session. The backend
   * uses this to create/find the user record for the given tenant.
   * Required when the user is not authenticated.
   * Sent as a query parameter to the streaming and send-message endpoints.
   */
  source?: string;

  /**
   * Ticket ID for authenticated users with an event ticket.
   *
   * When provided, the backend resolves the user's tenant and event from
   * the ticket. Only relevant for authenticated users.
   */
  ticketId?: string;

  /**
   * User geolocation context sent as the `X-User-Context` header.
   *
   * The backend expects a Base64-encoded JSON object with `lat` and `lng`.
   * The SDK handles the encoding automatically when this object is provided.
   *
   * @example
   * ```typescript
   * userContext: { lat: 40.4168, lng: -3.7038 }
   * ```
   */
  userContext?: {
    /** Latitude coordinate (-90 to 90) */
    lat: number;
    /** Longitude coordinate (-180 to 180) */
    lng: number;
  };

  // === Rate Limiting ===
  /**
   * Client-side rate limiter configuration.
   *
   * Controls how many messages the user can send within a time window
   * before being temporarily throttled. This is a client-side safety net
   * to prevent accidental spam; the backend enforces its own limits
   * independently.
   *
   * When omitted, sensible defaults are used (10 messages per minute,
   * 5-second cooldown after hitting the limit).
   *
   * @example
   * ```typescript
   * rateLimit: {
   *   maxRequests: 5,      // 5 messages per window
   *   windowMs: 30000,     // 30-second window
   *   cooldownMs: 10000,   // 10-second cooldown
   * }
   * ```
   */
  rateLimit?: {
    /** Maximum messages per time window. Default: 10 */
    maxRequests?: number;
    /** Time window in milliseconds. Default: 60000 (1 minute) */
    windowMs?: number;
    /** Cooldown after hitting the limit in milliseconds. Default: 5000 (5 seconds) */
    cooldownMs?: number;
  };

  // === Authentication ===
  /**
   * Authentication configuration for identified user sessions.
   *
   * When provided, the widget switches from anonymous (public) mode to
   * authenticated mode, enabling user-specific features such as conversation
   * history, personalised responses, and identity-aware interactions.
   *
   * When omitted, the widget operates in public mode using only the
   * `X-API-Key` header (existing default behaviour).
   *
   * @example
   * ```typescript
   * auth: {
   *   mode: 'jwt',
   *   token: 'eyJhbGciOiJIUzI1NiIs...',
   *   userIdentity: { userId: 'user_456', name: 'John Doe' },
   *   onTokenRefresh: async () => {
   *     const res = await fetch('/api/auth/refresh');
   *     const { token } = await res.json();
   *     return token;
   *   },
   * }
   * ```
   */
  auth?: AuthConfig;

  // === Callbacks ===
  /** Fired when the chat window opens */
  onOpen?: () => void;
  /** Fired when the chat window closes */
  onClose?: () => void;
  /** Fired when a new message is sent or received */
  onMessage?: (message: ChatMessage) => void;
  /** Fired when an API error occurs */
  onError?: (error: ChatbotError) => void;
  /** Fired when the widget has fully initialized and is ready for interaction */
  onReady?: () => void;
}

// ============================================================================
// API DTOs (Data Transfer Objects)
// ============================================================================

/**
 * Request body for creating a new conversation session.
 * Sent to: `POST /public/chatbot/{chatbotId}/conversation`
 */
export interface CreateConversationRequest {
  /** Tenant identifier */
  tenantId: string;
  /** Optional visitor identifier for session tracking */
  visitorId?: string;
  /** Optional metadata to attach to the conversation */
  metadata?: Record<string, unknown>;
  /** Locale preference for server-side responses */
  locale?: SupportedLocale;
  /** User identity for authenticated sessions (sent so the bot knows who the user is) */
  userIdentity?: UserIdentity;
}

/**
 * Response from creating a new conversation.
 */
export interface CreateConversationResponse {
  /** Unique conversation identifier */
  conversationId: string;
  /** Initial welcome message from the chatbot */
  welcomeMessage?: ChatMessage;
  /** Server timestamp of conversation creation */
  createdAt: string;
  /** Session token for this conversation (if different from config token) */
  sessionToken?: string;
}

/**
 * Request body for sending a user message.
 *
 * When using the streaming endpoint (`POST /chatbot/stream`), the backend
 * expects a `MessageRequest` with `message` and optional `ticketId`.
 * Additional context is sent via query params (`eventId`, `source`) and
 * headers (`X-Tenant-ID`, `X-User-Context`).
 *
 * For backward compatibility with custom endpoint configurations, the
 * `content` field is kept as an alias for integrations that use the
 * legacy `/public/chatbot/...` endpoints.
 */
export interface SendMessageRequest {
  /** The user's message text content (used by legacy endpoints) */
  content: string;
  /** Type of message being sent. Default: 'text' */
  type?: MessageType;
  /** Optional metadata to attach to the message */
  metadata?: Record<string, unknown>;
}

/**
 * Request body matching the backend `MessageRequest` DTO.
 *
 * Sent to: `POST /chatbot/stream` and `POST /chatbot/send-message`
 *
 * @see StreamingChatbotController in nev-api
 */
export interface BackendMessageRequest {
  /** The user's message text content (required) */
  message: string;
  /** Ticket ID for authenticated users with an event ticket (optional) */
  ticketId?: string;
}

/**
 * A single SSE event emitted by the backend streaming endpoint.
 *
 * Wire format example:
 * ```
 * event: token
 * data: {"type":"TOKEN","content":"Hello","timestamp":1234567890,"metadata":null}
 * ```
 *
 * @see StreamingChatEvent in nev-api
 */
export interface BackendStreamEvent {
  /** Event type: TOKEN, THINKING, DONE, ERROR, TOOL_CALL_START, TOOL_CALL_RESULT */
  type: BackendStreamEventType;
  /** Text content for TOKEN events, error message for ERROR events */
  content?: string | null;
  /** Metadata for TOOL_CALL events */
  metadata?: unknown;
  /** Timestamp in milliseconds since epoch */
  timestamp: number;
}

/**
 * Event types emitted by the backend streaming API.
 *
 * Maps 1:1 to `StreamingChatEvent.EventType` enum in nev-api.
 */
export type BackendStreamEventType =
  | 'TOKEN'
  | 'THINKING'
  | 'DONE'
  | 'ERROR'
  | 'TOOL_CALL_START'
  | 'TOOL_CALL_RESULT'
  | 'TYPING_START'
  | 'TYPING_STOP';

/**
 * Feedback type for chatbot message feedback (thumbs up/down).
 *
 * Maps to the backend `FeedbackType` enum: POSITIVE or NEGATIVE.
 */
export type FeedbackType = 'POSITIVE' | 'NEGATIVE';

/**
 * Response from sending a message, includes the bot's reply.
 */
export interface SendMessageResponse {
  /** The user's message as stored on the server */
  userMessage: ChatMessage;
  /** The bot's response message */
  botMessage: ChatMessage;
  /** Quick reply suggestions for the user's next interaction */
  quickReplies?: QuickReply[];
}

/**
 * Response from fetching conversation message history.
 * Returned by: `GET /public/chatbot/{chatbotId}/conversation/{conversationId}/messages`
 */
export interface GetMessagesResponse {
  /** Array of messages in chronological order */
  messages: ChatMessage[];
  /** Total number of messages in the conversation */
  total: number;
  /** Whether there are more messages available (pagination) */
  hasMore: boolean;
  /** Cursor for pagination - pass as query param to get next page */
  cursor?: string;
}

/**
 * Parameters for fetching messages with pagination.
 */
export interface GetMessagesParams {
  /** Maximum number of messages to return. Default: 50 */
  limit?: number;
  /** Pagination cursor from a previous response */
  cursor?: string;
  /** Sort order. Default: 'asc' (oldest first) */
  order?: 'asc' | 'desc';
}

// ============================================================================
// Error Types
// ============================================================================

/**
 * Chatbot-specific error structure.
 * Extends the concept of ApiError with chatbot-relevant error codes.
 *
 * @example
 * ```typescript
 * const error: ChatbotError = {
 *   code: 'RATE_LIMIT_EXCEEDED',
 *   message: 'You are sending messages too quickly. Please wait a moment.',
 *   status: 429,
 * };
 * ```
 */
export interface ChatbotError {
  /** Machine-readable error code for programmatic handling */
  code: ChatbotErrorCode;
  /** Human-readable error message */
  message: string;
  /** HTTP status code (if applicable) */
  status?: number;
  /** Additional error details for debugging */
  details?: Record<string, unknown>;
}

/**
 * Standardized error codes for chatbot operations.
 */
export type ChatbotErrorCode =
  | 'NETWORK_ERROR'
  | 'API_ERROR'
  | 'CONFIG_LOAD_FAILED'
  | 'CONVERSATION_CREATE_FAILED'
  | 'MESSAGE_SEND_FAILED'
  | 'MESSAGE_LOAD_FAILED'
  | 'RATE_LIMIT_EXCEEDED'
  | 'RATE_LIMITED'
  | 'INVALID_CONFIG'
  | 'CONTAINER_NOT_FOUND'
  | 'INITIALIZATION_FAILED'
  | 'CONVERSATION_EXPIRED'
  | 'SANITIZATION_ERROR'
  | 'STREAM_ERROR'
  | 'FEEDBACK_FAILED'
  | 'FILE_TOO_LARGE'
  | 'FILE_TYPE_NOT_ALLOWED'
  | 'UPLOAD_FAILED'
  | 'UNKNOWN_ERROR';

// ============================================================================
// Analytics Types
// ============================================================================

/**
 * Analytics event payload for chatbot interaction tracking.
 * Sent to the analytics endpoint via sendBeacon or fetch.
 */
export interface ChatbotAnalyticsEvent {
  /** Type of event being tracked */
  type: ChatbotEventType;
  /** Chatbot identifier */
  chatbotId: string;
  /** Conversation identifier (when available) */
  conversationId?: string;
  /** ISO 8601 timestamp of the event */
  timestamp: string;
  /** Additional event-specific metadata */
  metadata?: Record<string, unknown>;
}

/**
 * Extended analytics metadata for message-related events.
 */
export interface MessageAnalyticsMetadata {
  /** Message identifier */
  messageId: string;
  /** Role of the message sender */
  role: MessageRole;
  /** Length of the message content in characters */
  contentLength: number;
  /** Whether the message contains rich content */
  hasRichContent: boolean;
  /** Whether the message includes quick replies */
  hasQuickReplies: boolean;
  /** Response time in milliseconds (for bot messages) */
  responseTimeMs?: number;
}

// ============================================================================
// Internal State Types
// ============================================================================

/**
 * Internal state of the chatbot conversation.
 * Managed by the StateManager and optionally persisted to localStorage.
 */
export interface ConversationState {
  /** Current conversation (null when no active conversation) */
  conversation: Conversation | null;
  /** Whether the chat window is currently open */
  isOpen: boolean;
  /** Whether a message is being sent or a response is being awaited */
  isLoading: boolean;
  /** Whether the bot typing indicator is active */
  isTyping: boolean;
  /** Current error state (null when no error) */
  error: ChatbotError | null;
  /** Number of unread messages (reset when chat is opened) */
  unreadCount: number;
  /** ISO 8601 timestamp of the last user or bot activity */
  lastActivity: string | null;
}

/**
 * Serializable subset of ConversationState for localStorage persistence.
 * Excludes runtime-only fields like isLoading, isTyping, and error.
 */
export interface PersistedConversationState {
  /** Conversation identifier for resumption */
  conversationId: string;
  /** Chatbot identifier this conversation belongs to */
  chatbotId: string;
  /** Cached messages for instant display before API sync */
  messages: ChatMessage[];
  /** ISO 8601 timestamp of last activity for TTL calculation */
  lastActivity: string;
  /** Conversation metadata */
  metadata?: Record<string, unknown>;
}

// ============================================================================
// i18n Types
// ============================================================================

/**
 * Complete set of translatable strings for the chatbot UI.
 * Each supported locale provides a full implementation of this interface.
 */
export interface ChatbotTranslations extends Record<string, string> {
  /** Input placeholder text (e.g., "Type a message...") */
  inputPlaceholder: string;
  /** Send button accessible label */
  sendButton: string;
  /** Chat window title when no name is configured */
  defaultTitle: string;
  /** Status text shown when online */
  statusOnline: string;
  /** Status text shown when connecting */
  statusConnecting: string;
  /** Status text shown when offline/disconnected */
  statusOffline: string;
  /** Typing indicator text (e.g., "is typing...") */
  typingIndicator: string;
  /** Error message shown when a message fails to send */
  messageSendError: string;
  /** Error message shown when connection to server fails */
  connectionError: string;
  /** Error message shown when rate limit is hit */
  rateLimitError: string;
  /** Rate limit error with countdown (uses {seconds} placeholder) */
  rateLimitCountdown: string;
  /** "Powered by Nevent" branding text */
  poweredBy: string;
  /** New conversation button text */
  newConversation: string;
  /** Close chat button accessible label */
  closeChat: string;
  /** Open chat button accessible label */
  openChat: string;
  /** Retry button text shown on message send failure */
  retry: string;
  /** Timestamp label for "just now" */
  justNow: string;
  /** Timestamp label for "X minutes ago" */
  minutesAgo: string;
  /** Timestamp label for "X hours ago" */
  hoursAgo: string;
  /** Timestamp label for "yesterday" */
  yesterday: string;
  /** Banner text shown when the browser has no internet connection */
  connectionOffline: string;
  /** Banner text shown while the widget is attempting to reconnect */
  connectionReconnecting: string;
  /** Banner text shown briefly after a successful reconnection */
  connectionReconnected: string;
  /** Accessible label for the attachment (paperclip) button */
  attachFile: string;
  /** Accessible label prefix for the remove button on file previews */
  removeFile: string;
  /** Label shown during file upload progress */
  uploading: string;
  /** Error message when a file exceeds the size limit (uses {maxMB} placeholder) */
  fileTooBig: string;
  /** Error message when a file type is not accepted */
  fileTypeNotAllowed: string;
  /** Error message when a file upload fails */
  uploadFailed: string;
  /** Hint text shown on the drag-and-drop overlay */
  dragDropHint: string;
  /** Typing indicator text with agent name (uses {name} placeholder) */
  agentTyping: string;
  /** Typing indicator text when agent name is unknown */
  someoneTyping: string;
  /** Accessible label for the "Powered by Nevent" branding link */
  brandingAriaLabel: string;
  /**
   * Accessible label for the header close/minimize button inside the chat window.
   * Distinct from `closeChat` (used on the FAB bubble) to avoid aria-label duplication
   * when both the bubble and the header button are visible simultaneously.
   */
  minimizeChat: string;
}

// ============================================================================
// Lifecycle & Event Types
// ============================================================================

/**
 * Widget lifecycle states.
 * Tracks the initialization and operational state of the widget.
 */
export type WidgetLifecycleState =
  | 'idle'
  | 'initializing'
  | 'loading_config'
  | 'ready'
  | 'error'
  | 'destroyed';

/**
 * Internal event types for the widget event bus.
 * Used for communication between widget components.
 */
export type WidgetInternalEvent =
  | 'state:changed'
  | 'config:loaded'
  | 'conversation:created'
  | 'conversation:resumed'
  | 'message:sent'
  | 'message:received'
  | 'message:error'
  | 'ui:open'
  | 'ui:close'
  | 'ui:toggle'
  | 'typing:start'
  | 'typing:stop'
  | 'error:occurred'
  | 'widget:ready'
  | 'widget:destroyed';

/**
 * Callback map for widget internal events.
 */
export interface WidgetEventMap {
  'state:changed': ConversationState;
  'config:loaded': ServerChatbotConfig;
  'conversation:created': Conversation;
  'conversation:resumed': Conversation;
  'message:sent': ChatMessage;
  'message:received': ChatMessage;
  'message:error': ChatbotError;
  'ui:open': void;
  'ui:close': void;
  'ui:toggle': void;
  'typing:start': void;
  'typing:stop': void;
  'error:occurred': ChatbotError;
  'widget:ready': void;
  'widget:destroyed': void;
}

// ============================================================================
// CSS Generation Types
// ============================================================================

/**
 * CSS class name constants for the chatbot widget.
 * Used by the CSS generator and UI renderers for consistent class naming.
 */
export interface CSSClassNames {
  /** Root widget container */
  root: string;
  /** Floating bubble element */
  bubble: string;
  /** Unread count badge */
  badge: string;
  /** Chat window container */
  window: string;
  /** Window header */
  header: string;
  /** Header avatar */
  headerAvatar: string;
  /** Header title */
  headerTitle: string;
  /** Header subtitle */
  headerSubtitle: string;
  /** Close button */
  closeButton: string;
  /** Message list container */
  messageList: string;
  /** Individual message wrapper */
  message: string;
  /** User message modifier */
  messageUser: string;
  /** Bot message modifier */
  messageBot: string;
  /** System message modifier */
  messageSystem: string;
  /** Message content */
  messageContent: string;
  /** Message timestamp */
  messageTimestamp: string;
  /** Message avatar */
  messageAvatar: string;
  /** Input area container */
  inputArea: string;
  /** Text input field */
  inputField: string;
  /** Send button */
  sendButton: string;
  /** Typing indicator container */
  typingIndicator: string;
  /** Typing indicator dot */
  typingDot: string;
  /** Quick reply container */
  quickReplies: string;
  /** Quick reply button */
  quickReplyButton: string;
  /** Rich content container */
  richContent: string;
  /** Card element */
  card: string;
  /** Carousel container */
  carousel: string;
  /** Branding footer */
  branding: string;
  /** Error message */
  errorMessage: string;
  /** Loading state */
  loading: string;
  /** Hidden state */
  hidden: string;
  /** Open state */
  open: string;
  /** Fullscreen mode (mobile) */
  fullscreen: string;
}

// ============================================================================
// Re-exports from @nevent/core
// ============================================================================

/**
 * Re-export ApiError from core for convenience.
 * Consumers can import chatbot-specific ChatbotError or the generic ApiError.
 */
export type { ApiError };

/**
 * Re-export authentication types from auth-manager for convenience.
 * Consumers can import these directly from `@nevent/chatbot`.
 */
export type {
  AuthConfig,
  AuthMode,
  UserIdentity,
} from './chatbot/auth-manager';
